/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "keyxx.core.go"
 #include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void Init(int m_in, int n_in, int q_in, int p_in);
extern __declspec(dllexport) void InitCodeType(int ct);
extern __declspec(dllexport) void InitSerializeType(int st);
extern __declspec(dllexport) void InitStrCaseChangeMode(int scc);
extern __declspec(dllexport) void InitIsFastString(int iss);
extern __declspec(dllexport) char* SM3(char* input);
extern __declspec(dllexport) void LoadPrivKey(char* skbfile);
extern __declspec(dllexport) void LoadPubKey(char* pkbfile);
extern __declspec(dllexport) void LoadDictionary(char* dictbfile);
extern __declspec(dllexport) void LoadPrivKeyString(char* skbstring);
extern __declspec(dllexport) void LoadPubKeyString(char* pkbstring);
extern __declspec(dllexport) void LoadDictionaryString(char* dictbstring);
extern __declspec(dllexport) void LoadBiasKey(char* bkfile);
extern __declspec(dllexport) void LoadExKey(char* dictExbfile);
extern __declspec(dllexport) void LoadPrivkeyFloat(char* skffile);
extern __declspec(dllexport) void LoadDictionaryFloat(char* dictffile);
extern __declspec(dllexport) void LoadExpressionBlockKeys();
extern __declspec(dllexport) void LoadExpressionFloatKeys();
extern __declspec(dllexport) void InitExpression();
extern __declspec(dllexport) void ClearExpressionVariable();
extern __declspec(dllexport) void AddExpressionVariable(char* _name, char* _type, char* _value);
extern __declspec(dllexport) char* ExpressionCalculation(char* formula);
extern __declspec(dllexport) void GenSKB(int m, int n, int q, int p, char* filename);
extern __declspec(dllexport) void GenPKB(char* skbfile, char* filename);
extern __declspec(dllexport) void GenDictB(char* skbfile, char* filename, double delta);
extern __declspec(dllexport) char* GenSKBString(int m, int n, int q, int p);
extern __declspec(dllexport) char* GenPKBString(char* skbfile);
extern __declspec(dllexport) char* GenDictBString(char* skbfile, double delta);
extern __declspec(dllexport) void GenBK(int n, int q, int p, char* filename);
extern __declspec(dllexport) void GenDictExB(char* bkfile, char* pkbfile, char* dictbfile, char* filename);
extern __declspec(dllexport) void GenSKF(int p, char* filename);
extern __declspec(dllexport) void GenDictF(char* skffile, char* filename);
extern __declspec(dllexport) char* EncInt(int plain);
extern __declspec(dllexport) char* EncPubInt(int plain);
extern __declspec(dllexport) char* EncString(char* plain);
extern __declspec(dllexport) char* EncPubString(char* plain);
extern __declspec(dllexport) char* EncPubStringWithIndex(char* plain);
extern __declspec(dllexport) char* EncFloat(double plain);
extern __declspec(dllexport) char* EncDouble(double plain);
extern __declspec(dllexport) char* EncPubDouble(double plain);
extern __declspec(dllexport) char* EncBinary(int plain, int l);
extern __declspec(dllexport) char* EncPubBinary(int plain, int l);
extern __declspec(dllexport) int DecInt(char* input);
extern __declspec(dllexport) double DecFloat(char* input);
extern __declspec(dllexport) double DecDouble(char* input);
extern __declspec(dllexport) char* Decrypt(char* input);
extern __declspec(dllexport) int DecBinary(char* input);
extern __declspec(dllexport) char* GenSign(char* input);
extern __declspec(dllexport) int VerifySign(char* input, char* sign);
extern __declspec(dllexport) char* AddCipherInt(char* c1, char* c2);
extern __declspec(dllexport) char* SubCipherInt(char* c1, char* c2);
extern __declspec(dllexport) char* MulCipherInt(char* c1, char* c2);
extern __declspec(dllexport) char* AddCipherFloat(char* c1, char* c2);
extern __declspec(dllexport) char* SubCipherFloat(char* c1, char* c2);
extern __declspec(dllexport) char* MulCipherFloat(char* c1, char* c2);
extern __declspec(dllexport) char* DivCipherFloat(char* c1, char* c2);
extern __declspec(dllexport) char* AddCipherDouble(char* c1, char* c2);
extern __declspec(dllexport) char* SubCipherDouble(char* c1, char* c2);
extern __declspec(dllexport) char* MulCipherDouble(char* c1, char* c2);
extern __declspec(dllexport) char* DivCipherDouble(char* c1, char* c2);
extern __declspec(dllexport) char* XORCipherBinary(char* c1, char* c2);
extern __declspec(dllexport) char* ANDCipherBinary(char* c1, char* c2);
extern __declspec(dllexport) char* ORCipherBinary(char* c1, char* c2);
extern __declspec(dllexport) char* NOTCipherBinary(char* c1);
extern __declspec(dllexport) char* ShiftLeftCipherBinary(char* c1, int _bias);
extern __declspec(dllexport) char* ShiftRightCipherBinary(char* c1, int _bias);
extern __declspec(dllexport) int CompareCipherInt(char* c1, char* c2);
extern __declspec(dllexport) int CompareCipherString(char* c1, char* c2);
extern __declspec(dllexport) int CompareCipherFloat(char* c1, char* c2);
extern __declspec(dllexport) int CompareCipherDouble(char* c1, char* c2);
extern __declspec(dllexport) char* ABSCipherFloat(char* c1);
extern __declspec(dllexport) char* PowCipherFloat(char* c1, int n);
extern __declspec(dllexport) char* SqrtCipherFloat(char* c1);
extern __declspec(dllexport) char* PowCipherFloat_FractionOrder(char* c1, int n, int m);
extern __declspec(dllexport) char* PowCipherFloat_RealOrder(char* c1, double a);
extern __declspec(dllexport) char* LogCipherFloat(char* c1);
extern __declspec(dllexport) char* ExpCipherFloat(char* c1);
extern __declspec(dllexport) char* SinCipherFloat(char* c1);
extern __declspec(dllexport) char* CosCipherFloat(char* c1);
extern __declspec(dllexport) char* TanCipherFloat(char* c1);
extern __declspec(dllexport) char* ArcsinCipherFloat(char* c1);
extern __declspec(dllexport) char* ArccosCipherFloat(char* c1);
extern __declspec(dllexport) char* ArctanCipherFloat(char* c1);
extern __declspec(dllexport) char* SinhCipherFloat(char* c1);
extern __declspec(dllexport) char* CoshCipherFloat(char* c1);
extern __declspec(dllexport) char* TanhCipherFloat(char* c1);
extern __declspec(dllexport) char* ArcsinhCipherFloat(char* c1);
extern __declspec(dllexport) char* ArccoshCipherFloat(char* c1);
extern __declspec(dllexport) char* ArctanhCipherFloat(char* c1);
extern __declspec(dllexport) char* ABSCipherDouble(char* c1);
extern __declspec(dllexport) char* PowCipherDouble(char* c1, int n);
extern __declspec(dllexport) char* SqrtCipherDouble(char* c1);
extern __declspec(dllexport) char* PowCipherDouble_FractionOrder(char* c1, int n, int m);
extern __declspec(dllexport) char* PowCipherDouble_RealOrder(char* c1, double a);
extern __declspec(dllexport) char* LogCipherDouble(char* c1);
extern __declspec(dllexport) char* ExpCipherDouble(char* c1);
extern __declspec(dllexport) char* SinCipherDouble(char* c1);
extern __declspec(dllexport) char* CosCipherDouble(char* c1);
extern __declspec(dllexport) char* TanCipherDouble(char* c1);
extern __declspec(dllexport) char* ArcsinCipherDouble(char* c1);
extern __declspec(dllexport) char* ArccosCipherDouble(char* c1);
extern __declspec(dllexport) char* ArctanCipherDouble(char* c1);
extern __declspec(dllexport) char* SinhCipherDouble(char* c1);
extern __declspec(dllexport) char* CoshCipherDouble(char* c1);
extern __declspec(dllexport) char* TanhCipherDouble(char* c1);
extern __declspec(dllexport) char* ArcsinhCipherDouble(char* c1);
extern __declspec(dllexport) char* ArccoshCipherDouble(char* c1);
extern __declspec(dllexport) char* ArctanhCipherDouble(char* c1);
extern __declspec(dllexport) char* ConcatString(char* data1, char* data2);
extern __declspec(dllexport) char* Substring(char* data, int start, int _end);
extern __declspec(dllexport) char* EncPubIntExtend(int plain);
extern __declspec(dllexport) char* EncPubStringExtend(char* plain);
extern __declspec(dllexport) char* TranEN(char* cipher);
extern __declspec(dllexport) char* TranStringEN(char* _cs);
extern __declspec(dllexport) char* DecStringNormal(char* _cs);
extern __declspec(dllexport) char* DecString(char* cs);
extern __declspec(dllexport) char* TranStringENMix(char* _cs);
extern __declspec(dllexport) char* AddByteExtend(char* cipher1, char* cipher2);
extern __declspec(dllexport) char* SubstractByteExtend(char* cipher1, char* cipher2);
extern __declspec(dllexport) char* MultiplyByteExtend(char* cipher1, char* cipher2);
extern __declspec(dllexport) char* EqualByteExtend(char* cipher1, char* cipher2);
extern __declspec(dllexport) char* CatCipherStringMix(char* _cs1, char* _cs2);
extern __declspec(dllexport) char* EqualStringExtend(char* _cs1, char* _cs2);
extern __declspec(dllexport) void FreePoint(void* cs);
extern __declspec(dllexport) int IsCipher(char* cipherstr);
extern __declspec(dllexport) int IsCipherInt(char* cipherstr);
extern __declspec(dllexport) int IsCipherFloat(char* cipherstr);
extern __declspec(dllexport) int IsCipherDouble(char* cipherstr);
extern __declspec(dllexport) int IsCipherString(char* cipherstr);
extern __declspec(dllexport) int IsCipherStringWithIndex(char* cipherstr);
extern __declspec(dllexport) int CompareStringWithIndex(char* c1, char* c2, int max);
extern __declspec(dllexport) char* EncStringWithIndex(char* c1);
extern __declspec(dllexport) char* DecStringWithIndex(char* input);

#ifdef __cplusplus
}
#endif
